openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Marketplace API"
paths:
  /marketplace/items:
    post:
      summary: "Add a new marketplace item"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MarketplaceItemReq"
      responses:
        201:
          description: Return item id if created successfully
          content:
            text/plain:
              schema:
                type: string
        405:
          $ref: "#/components/responses/InvalidInput"
    get:
      summary: "List marketplace items"
      parameters:
        - in: query
          name: author
          schema:
            type: string
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
        - in: query
          name: catagory
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketplaceItemRes"

  /marketplace/items/{itemId}:
    get:
      summary: "Get specific marketplace item info"
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketplaceItemRes"
        404:
          $ref: "#/components/responses/404NotFound"
    put:
      summary: "Update a marketplace item"
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MarketplaceItemReq"
      responses:
        200:
          description: OK
        404:
          $ref: "#/components/responses/404NotFound"
        405:
          $ref: "#/components/responses/InvalidInput"
    delete:
      summary: "delete a marketplace item"
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        404:
          $ref: "#/components/responses/404NotFound"
  /marketplace/items/{itemId}/tags:
    get:
      summary: "Get tags of specific marketplace item"
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tag"
        404:
          $ref: "#/components/responses/404NotFound"
    put:
      summary: "Update tags of a marketplace item"
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/MarketplaceItemReq"
      responses:
        200:
          description: OK
        404:
          $ref: "#/components/responses/404NotFound"
        405:
          $ref: "#/components/responses/InvalidInput"

components:
  schemas:
    MarketplaceItemReq:
      type: object
      properties:
        name:
          type: string
        author:
          type: string
        category:
          type: string
        introduction:
          type: string
        description:
          type: string
        jobConfig:
          type: object
        submits:
          type: number
        starNumber:
          type: number
        starUsers:
          type: array
          items:
            type: string
    MarketplaceItemRes:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        author:
          type: string
        createdAt:
          type: string
          format: "date-time"
        updatedAt:
          type: string
          format: "date-time"
        category:
          type: string
        introduction:
          type: string
        description:
          type: string
        jobConfig:
          type: object
        submits:
          type: number
        starNumber:
          type: number
        starUsers:
          type: array
          items:
            type: string
    Tag:
      type: object
      properties:
        value:
          type: string

  responses:
    404NotFound:
      description: The specified resource was not found.
    InvalidInput:
      description: Invalid input
